services:
  client:
    image: client:latest
    build: ./client
    container_name: client
    ports: 
    - 5173:5173
  server:
    image: server:latest
    build: ./_server
    container_name: server
    ports:
    - 8000:8000
    environment:
    - ASSET_URL=http://localhost:5173