# Generated by Django 5.0.3 on 2024-05-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='Comment', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
